Repository Koreyoshi159/SDG-Tool, pull requests merged in 2021-05, with the labels that each got.

#80 admin panel additions
  app/Http/Controllers/BlogController.php
  app/Http/Controllers/ProgramController.php
  phpunit.xml
  resources/views/admin.blade.php
  resources/views/blogs/edit.blade.php
  resources/views/common/navbar.blade.php
  resources/views/programs/edit.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: High Priority, enhancement

#101 Added title and admin can edit excerpts from SDG pages
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/BlogController.php
  app/Http/Controllers/SdgController.php
  app/Models/Sdg.php
  database/migrations/2021_03_30_100637_create_sdgs_table.php
  database/migrations/2021_03_30_100707_create_blogs_table.php
  database/seeders/SdgSeeder.php
  public/css/app.css
  resources/views/admin.blade.php
  resources/views/blogs/create.blade.php
  resources/views/blogs/edit.blade.php
  resources/views/blogs/index.blade.php
  resources/views/sdgs/edit.blade.php
  resources/views/sdgs/show.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: Admin, High Priority

#100 Create filter option
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/BlogController.php
  app/Http/Controllers/ProgramController.php
  app/Http/Controllers/ResearchGroupController.php
  app/Providers/AuthServiceProvider.php
  database/seeders/BusinessOperationSeeder.php
  package-lock.json
  public/css/app.css
  public/js/blog.js
  resources/views/blogs/index.blade.php
  resources/views/common/master.blade.php
  routes/web.php
Labels: High Priority
